version: '3.8'

services:
  next-app:
    container_name: next-app-development
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
      target: run
    volumes:
      - ./:/app
    ports:
      - 3000:3000
