version: '3.8'

services:
  next-app:
    container_name: next-app-production
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
      target: run
    ports:
      - 3000:3000

  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - next-app
