name: Docker build and publish image

on:
  workflow_dispatch:
    inputs:
      image_environment:
        description: 'Image environment'
        required: true
        type: choice
        options:
          - production
          - development

  workflow_call:

jobs:
  docker-build-and-publish-image:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Build image
        run: docker build --file ./docker/${{ inputs.image_environment }}/Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ inputs.image_environment }} .

      - name: Login to docker registry
        env:
          LOGIN: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: docker login ${{ env.REGISTRY }} --username ${{ env.LOGIN }} --password ${{ env.PASSWORD }}

      - name: Publish image to GitHub Packages
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.image_environment }}
