name: Docker build and publish image

on:
  workflow_dispatch:
    inputs:
      image_environment:
        description: 'Image environment'
        required: true
        type: choice
        options:
          - production
          - development

  workflow_call:

jobs:
  docker-build-and-publish-image:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build image
        run: docker build --file ./docker/${{ inputs.image_environment }}/Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ inputs.image_environment }} .

      - name: Login to registry
        run: docker login ${{ env.REGISTRY }} --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: Tag image
        run: docker tag ${{ env.IMAGE_NAME }}:${{ inputs.image_environment }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.image_environment }}

      - name: Publish image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.image_environment }}

      - name: Install axios
        run: rm package.json package-lock.json && npm install axios

      - name: Remove old image versions
        env:
          PACKAGE_TYPE: container
          PACKAGE_NAME: docker-nginx-rpi
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node ./.github/workflows/utils/deletePackages.mjs
